/** Input provenance, attached by the application rather than generated by an LLM. */
export interface RagSource {
  rank: number;
  documentId: string;
  chunkId: string;
  originalFilename: string;
  chunkIndex: number;
  pageNumbers: number[];
  similarity: number;
  excerpt: string;
  excerptTruncated: boolean;
}

export interface RagSummary {
  status: "generated" | "insufficient_context";
  model: string | null;
  retrievedChunkCount: number;
  contextChunkCount: number;
  contextBytes: number;
}
